from app.db.base_class import Base  # noqa: F401
from app.db.tables import GCFT  # noqa: F401
from app.db.tables import Client  # noqa: F401
from app.db.tables import ClientWebsite  # noqa: F401
from app.db.tables import GCFTSnap  # noqa: F401
from app.db.tables import GCFTSnapActiveDuration  # noqa: F401
from app.db.tables import GCFTSnapBrowserReport  # noqa: F401
from app.db.tables import GCFTSnapHotspotClick  # noqa: F401
from app.db.tables import GCFTSnapTrafficSource  # noqa: F401
from app.db.tables import GCFTSnapView  # noqa: F401
from app.db.tables import GeoCoord  # noqa: F401
from app.db.tables import GoogleAnalytics4Property  # noqa: F401
from app.db.tables import GoogleAnalytics4Stream  # noqa: F401
from app.db.tables import GoogleCloudProperty  # noqa: F401
from app.db.tables import GoogleSearchConsoleCountry  # noqa: F401
from app.db.tables import GoogleSearchConsoleDevice  # noqa: F401
from app.db.tables import GoogleSearchConsolePage  # noqa: F401
from app.db.tables import GoogleSearchConsoleProperty  # noqa: F401
from app.db.tables import GoogleSearchConsoleQuery  # noqa: F401
from app.db.tables import GoogleSearchConsoleSearchAppearance  # noqa: F401
from app.db.tables import GoogleUniversalAnalyticsProperty  # noqa: F401
from app.db.tables import GoogleUniversalAnalyticsView  # noqa: F401
from app.db.tables import ImageUpload  # noqa: F401
from app.db.tables import IpAddress  # noqa: F401
from app.db.tables import Item  # noqa: F401
from app.db.tables import Note  # noqa: F401
from app.db.tables import SharpSpring  # noqa: F401
from app.db.tables import User  # noqa: F401
from app.db.tables import UserClient  # noqa: F401
from app.db.tables import UserIpAddress  # noqa: F401
from app.db.tables import Website  # noqa: F401
from app.db.tables import WebsiteKeywordCorpus  # noqa: F401
from app.db.tables import WebsiteMap  # noqa: F401
from app.db.tables import WebsitePage  # noqa: F401
from app.db.tables import WebsitePageSpeedInsights  # noqa: F401
