repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python) 
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3
  