[tool.poetry]
name = "gcapi-backend"
version = "0.1.0"
description = ""
authors = ["Joey Grable <hello@joeygrable.com>"]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = {version = "0.20.0", extras = ["standard"]}
gunicorn = "^20.1.0"
greenlet = "2.0.1"
requests = "^2.28.1"
cryptography = "39.0.0"
bcrypt = "^4.0.0"
passlib = "^1.7.4"
fastapi = "0.86.0"
fastapi-mail = "^1.1.4"
pydantic = {version = "1.10.2", extras = ["email"]}
python-multipart = "0.0.5"
python-dotenv = "0.21.0"
PyMySQL = "1.0.2"
SQLAlchemy = {version = "1.4.46", extras = ["mypy", "asyncio"]}
sqlalchemy-stubs = "0.4"
SQLAlchemy-Utils = "0.38.3"
databases = "0.6.1"
PyJWT = "^2.4.0"
alembic = "1.8.1"
asgi-correlation-id = "^3.2.1"
asgi-lifespan = "^2.0.0"
anyio = {version = "3.6.2", extras = ["trio"]}
asyncio = "3.4.3"
aiohttp = "3.8.3"
aiosqlite = "0.18.0"
aiomysql = "0.1.1"
aiofiles = "22.1.0"
email-validator = "1.3.0"
Jinja2 = "3.1.2"
types-passlib = "^1.7.7"
fastapi-permissions = "^0.2.7"

[tool.poetry.dev-dependencies]
httpx = "0.23.3"
httpx-oauth = "0.10.2"
pytest = "7.2.0"
pytest-asyncio = "0.20.3"
pytest-cov = "4.0.0"
pytest-mock = "3.10.0"
autopep8 = "2.0.0"
pep8 = "1.7.1"
mypy = "0.991"
isort = "5.11.4"
black = "22.12.0"
flake8 = "6.0.0"
autoflake = "1.7.7"
makefun = "^1.14.0"
asgi-lifespan = "^2.0.0"

[tool.isort]
profile = "black"
src_paths = ["app"]
combine_as_imports = true
line_length = 88

[tool.black]
profile = "black"
src_paths = ["app"]
combine_as_imports = true
line_length = 88

[tool.mypy]
python_version = 3.11
ignore_missing_imports = false
disallow_untyped_defs = true
allow_redefinition = true
plugins = '''
    pydantic.mypy,
    sqlalchemy.ext.mypy.plugin,
    sqlmypy
'''

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true
exclude='''
    __init__.py
'''

[tool.flake8]
max-line-length = 88
exclude = '''
    .git,
    __pycache__,
    .mypy_cache,
    .pytest_cache
'''

[tool.pytest.ini_options]
testpaths = "tests"
filterwarnings = "error"
plugins = '''
    --cov-config=.coveragerc
    --cov=app
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --no-cov-on-fail
    --asyncio-mode=auto
    tests
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
