"""updated hotspot_content

Revision ID: 06ebefa81a2b
Revises: b7f0de526452
Create Date: 2024-10-29 22:36:24.996539

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

from app.db.custom_types.longtext import LongText

# revision identifiers, used by Alembic.
revision = '06ebefa81a2b'
down_revision = 'b7f0de526452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcft_snap_hotspotclick', 'hotspot_content',
               existing_type=sa.BLOB(),
               type_=LongText(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcft_snap_hotspotclick', 'hotspot_content',
               existing_type=LongText(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
