"""updated table tracking_link and client_tracking_link

Revision ID: 079ba740b9e5
Revises: 88e10e674783
Create Date: 2024-08-06 11:21:46.473815

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types.uuid import UUIDType  # type: ignore

from app.db.custom_types.longtext import LongText  # type: ignore

# revision identifiers, used by Alembic.
revision = '079ba740b9e5'
down_revision = '88e10e674783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_link',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('url_hash', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tracking_link_id'), 'tracking_link', ['id'], unique=True)
    op.create_table('client_tracking_link',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('client_id', UUIDType(binary=False), nullable=False),
    sa.Column('tracking_link_id', UUIDType(binary=False), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_link.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'tracking_link_id')
    )
    op.create_index(op.f('ix_client_tracking_link_id'), 'client_tracking_link', ['id'], unique=True)
    op.alter_column('client_report', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=True)
    op.drop_index('ix_data_bucket_bucket_prefix', table_name='data_bucket')
    op.alter_column('go_sc_country', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_device', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_page', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_query', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_searchappearance', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_searchappearance', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_query', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_page', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_device', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_country', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.create_index('ix_data_bucket_bucket_prefix', 'data_bucket', ['bucket_prefix'], unique=True)
    op.alter_column('client_report', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_index(op.f('ix_client_tracking_link_id'), table_name='client_tracking_link')
    op.drop_table('client_tracking_link')
    op.drop_index(op.f('ix_tracking_link_id'), table_name='tracking_link')
    op.drop_table('tracking_link')
    # ### end Alembic commands ###
