"""added styleguide column to clients table

Revision ID: 1bc48e91aa39
Revises: 7a61307f0405
Create Date: 2024-09-18 13:00:17.957395

"""

import sqlalchemy as sa
from sqlalchemy_utils.types.json import JSONType

from alembic import op

# revision identifiers, used by Alembic.
revision = "1bc48e91aa39"
down_revision = "7a61307f0405"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("style_guide", JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "style_guide")
    # ### end Alembic commands ###
