"""update bdx_feed with xml_file_key

Revision ID: 355f1987cdd3
Revises: c8a2683f41b6
Create Date: 2024-05-11 21:35:31.296853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355f1987cdd3'
down_revision = 'c8a2683f41b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bdx_feed', sa.Column('xml_file_key', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_bdx_feed_xml_file_key'), 'bdx_feed', ['xml_file_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bdx_feed_xml_file_key'), table_name='bdx_feed')
    op.drop_column('bdx_feed', 'xml_file_key')
    # ### end Alembic commands ###
