"""switched go ads relationship with websites to many-to-many

Revision ID: 4087de0ca8d4
Revises: 50b5629e4853
Create Date: 2025-01-26 08:42:06.964389

"""

import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op

# revision identifiers, used by Alembic.
revision = "4087de0ca8d4"
down_revision = "50b5629e4853"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "website_go_ads",
        sa.Column("website_id", UUIDType(binary=False), nullable=False),
        sa.Column("go_ads_id", UUIDType(binary=False), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["go_ads_id"],
            ["go_ads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["website.id"],
        ),
        sa.PrimaryKeyConstraint("website_id", "go_ads_id"),
    )
    op.drop_constraint("go_ads_ibfk_3", "go_ads", type_="foreignkey")
    op.drop_column("go_ads", "website_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("go_ads", sa.Column("website_id", sa.CHAR(length=32), nullable=False))
    op.create_foreign_key("go_ads_ibfk_3", "go_ads", "website", ["website_id"], ["id"])
    op.drop_table("website_go_ads")
    # ### end Alembic commands ###
