"""added is_active flag to client, note, website tables

Revision ID: 4361e9f96696
Revises: 7a37c4da2a88
Create Date: 2023-09-28 16:36:54.976188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4361e9f96696'
down_revision = '7a37c4da2a88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'geocoord', ['address'])
    op.add_column('note', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    op.add_column('website', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4000000000),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4000000000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=sa.Text(length=4000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=sa.Text(length=4000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.drop_column('website', 'is_active')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('note', 'is_active')
    op.drop_constraint(None, 'geocoord', type_='unique')
    op.drop_column('client', 'is_active')
    # ### end Alembic commands ###
