"""removed mysql dependencies to pass sqlite tests

Revision ID: 4bb1a741a074
Revises: 62f1a9ce7b95
Create Date: 2023-09-19 21:31:53.176544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bb1a741a074'
down_revision = '62f1a9ce7b95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4000000000),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4000000000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=sa.Text(length=4000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=sa.Text(length=4000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
