"""removed go_sc metrics and removed unnecessary id from secondary join tables

Revision ID: 50b5629e4853
Revises: a006ff43d0a4
Create Date: 2025-01-26 08:26:32.772150

"""

import sqlalchemy as sa

from alembic import op
from app.db.custom_types.longtext import LongText

# revision identifiers, used by Alembic.
revision = "50b5629e4853"
down_revision = "a006ff43d0a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_go_sc_searchappearance_id", table_name="go_sc_searchappearance")
    op.drop_index(
        "ix_go_sc_searchappearance_title", table_name="go_sc_searchappearance"
    )
    op.drop_table("go_sc_searchappearance")
    op.drop_index("ix_go_sc_device_id", table_name="go_sc_device")
    op.drop_index("ix_go_sc_device_title", table_name="go_sc_device")
    op.drop_table("go_sc_device")
    op.drop_index("ix_go_sc_country_id", table_name="go_sc_country")
    op.drop_index("ix_go_sc_country_title", table_name="go_sc_country")
    op.drop_table("go_sc_country")
    op.drop_index("ix_go_sc_query_id", table_name="go_sc_query")
    op.drop_index("ix_go_sc_query_title", table_name="go_sc_query")
    op.drop_table("go_sc_query")
    op.drop_index("ix_go_sc_page_id", table_name="go_sc_page")
    op.drop_index("ix_go_sc_page_title", table_name="go_sc_page")
    op.drop_table("go_sc_page")
    op.drop_index("ix_client_platform_id", table_name="client_platform")
    op.drop_column("client_platform", "id")
    op.drop_index("ix_client_website_id", table_name="client_website")
    op.drop_column("client_website", "id")
    op.drop_index("ix_user_client_id", table_name="user_client")
    op.drop_column("user_client", "id")
    op.drop_index("ix_user_ipaddress_id", table_name="user_ipaddress")
    op.drop_column("user_ipaddress", "id")
    op.drop_index("ix_website_go_a4_id", table_name="website_go_a4")
    op.drop_column("website_go_a4", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("website_go_a4", sa.Column("id", sa.CHAR(length=32), nullable=False))
    op.create_index("ix_website_go_a4_id", "website_go_a4", ["id"], unique=True)
    op.add_column("user_ipaddress", sa.Column("id", sa.CHAR(length=32), nullable=False))
    op.create_index("ix_user_ipaddress_id", "user_ipaddress", ["id"], unique=True)
    op.add_column("user_client", sa.Column("id", sa.CHAR(length=32), nullable=False))
    op.create_index("ix_user_client_id", "user_client", ["id"], unique=True)
    op.add_column("client_website", sa.Column("id", sa.CHAR(length=32), nullable=False))
    op.create_index("ix_client_website_id", "client_website", ["id"], unique=True)
    op.add_column(
        "client_platform", sa.Column("id", sa.CHAR(length=32), nullable=False)
    )
    op.create_index("ix_client_platform_id", "client_platform", ["id"], unique=True)
    op.create_table(
        "go_sc_page",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("keys", LongText(), nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("impressions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ctr", sa.FLOAT(), nullable=False),
        sa.Column("position", sa.FLOAT(), nullable=False),
        sa.Column("date_start", sa.DATETIME(), nullable=False),
        sa.Column("date_end", sa.DATETIME(), nullable=False),
        sa.Column("gsc_id", sa.CHAR(length=32), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gsc_id"], ["go_sc.id"], name="go_sc_page_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_go_sc_page_title", "go_sc_page", ["title"], unique=False)
    op.create_index("ix_go_sc_page_id", "go_sc_page", ["id"], unique=True)
    op.create_table(
        "go_sc_query",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("keys", LongText(), nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("impressions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ctr", sa.FLOAT(), nullable=False),
        sa.Column("position", sa.FLOAT(), nullable=False),
        sa.Column("date_start", sa.DATETIME(), nullable=False),
        sa.Column("date_end", sa.DATETIME(), nullable=False),
        sa.Column("gsc_id", sa.CHAR(length=32), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gsc_id"], ["go_sc.id"], name="go_sc_query_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_go_sc_query_title", "go_sc_query", ["title"], unique=False)
    op.create_index("ix_go_sc_query_id", "go_sc_query", ["id"], unique=True)
    op.create_table(
        "go_sc_country",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("keys", LongText(), nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("impressions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ctr", sa.FLOAT(), nullable=False),
        sa.Column("position", sa.FLOAT(), nullable=False),
        sa.Column("date_start", sa.DATETIME(), nullable=False),
        sa.Column("date_end", sa.DATETIME(), nullable=False),
        sa.Column("gsc_id", sa.CHAR(length=32), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gsc_id"], ["go_sc.id"], name="go_sc_country_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_go_sc_country_title", "go_sc_country", ["title"], unique=False)
    op.create_index("ix_go_sc_country_id", "go_sc_country", ["id"], unique=True)
    op.create_table(
        "go_sc_device",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("keys", LongText(), nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("impressions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ctr", sa.FLOAT(), nullable=False),
        sa.Column("position", sa.FLOAT(), nullable=False),
        sa.Column("date_start", sa.DATETIME(), nullable=False),
        sa.Column("date_end", sa.DATETIME(), nullable=False),
        sa.Column("gsc_id", sa.CHAR(length=32), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["gsc_id"], ["go_sc.id"], name="go_sc_device_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_go_sc_device_title", "go_sc_device", ["title"], unique=False)
    op.create_index("ix_go_sc_device_id", "go_sc_device", ["id"], unique=True)
    op.create_table(
        "go_sc_searchappearance",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("keys", LongText(), nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("impressions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ctr", sa.FLOAT(), nullable=False),
        sa.Column("position", sa.FLOAT(), nullable=False),
        sa.Column("date_start", sa.DATETIME(), nullable=False),
        sa.Column("date_end", sa.DATETIME(), nullable=False),
        sa.Column("gsc_id", sa.CHAR(length=32), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gsc_id"], ["go_sc.id"], name="go_sc_searchappearance_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_go_sc_searchappearance_title",
        "go_sc_searchappearance",
        ["title"],
        unique=False,
    )
    op.create_index(
        "ix_go_sc_searchappearance_id", "go_sc_searchappearance", ["id"], unique=True
    )
    # ### end Alembic commands ###
