"""made client tracking link a one-to-many relationship

Revision ID: 5ad33d8352c3
Revises: d1c6da9a773a
Create Date: 2024-09-12 15:05:20.962827

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types.uuid import UUIDType

# revision identifiers, used by Alembic.
revision = '5ad33d8352c3'
down_revision = 'd1c6da9a773a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_tracking_link_id', table_name='client_tracking_link')
    op.drop_table('client_tracking_link')
    op.add_column('tracking_link', sa.Column('client_id', UUIDType(binary=False), nullable=False))
    op.create_foreign_key(None, 'tracking_link', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_link', type_='foreignkey')  # type: ignore
    op.drop_column('tracking_link', 'client_id')
    op.create_table('client_tracking_link',
        sa.Column('id', mysql.CHAR(length=32), nullable=False),
        sa.Column('client_id', mysql.CHAR(length=32), nullable=False),
        sa.Column('tracking_link_id', mysql.CHAR(length=32), nullable=False),
        sa.Column('created', mysql.DATETIME(), nullable=False),
        sa.Column('updated', mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='client_tracking_link_ibfk_1'),
        sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_link.id'], name='client_tracking_link_ibfk_2'),
        sa.PrimaryKeyConstraint('client_id', 'tracking_link_id'),
        mysql_default_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_client_tracking_link_id', 'client_tracking_link', ['id'], unique=True)
    # ### end Alembic commands ###
