"""updated tracking_links col str length

Revision ID: 64b9b1ebb3ee
Revises: 28c1293e8cb2
Create Date: 2024-08-07 11:46:48.717704

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

from app.db.custom_types.longtext import LongText  # type: ignore

# revision identifiers, used by Alembic.
revision = '64b9b1ebb3ee'
down_revision = '28c1293e8cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_report', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=True)
    op.alter_column('go_sc_country', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_device', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_page', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_query', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('go_sc_searchappearance', 'keys',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('tracking_link', 'url',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=3116),
               existing_nullable=False)
    op.alter_column('tracking_link', 'utm_campaign',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=704),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=704),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_medium',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=704),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_source',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=704),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_term',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=704),
               existing_nullable=True)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('tracking_link', 'utm_term',
               existing_type=sa.String(length=704),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_source',
               existing_type=sa.String(length=704),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_medium',
               existing_type=sa.String(length=704),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_content',
               existing_type=sa.String(length=704),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tracking_link', 'utm_campaign',
               existing_type=sa.String(length=704),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tracking_link', 'url',
               existing_type=sa.String(length=3116),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=False)
    op.alter_column('go_sc_searchappearance', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_query', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_page', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_device', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('go_sc_country', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('client_report', 'keys',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
