"""added website id to ga4 stream, removed from ga4 property

Revision ID: 67ab88f410ce
Revises: cce84fb59468
Create Date: 2024-04-27 16:11:39.934879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils  # type: ignore
from app.db.custom_types import LongText

# revision identifiers, used by Alembic.
revision = '67ab88f410ce'
down_revision = 'cce84fb59468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'go_a4', ['property_id'])
    op.drop_constraint('go_a4_ibfk_2', 'go_a4', type_='foreignkey')
    op.drop_column('go_a4', 'website_id')
    op.add_column('go_a4_stream', sa.Column('website_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.create_foreign_key(None, 'go_a4_stream', 'website', ['website_id'], ['id'])
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.drop_constraint(None, 'go_a4_stream', type_='foreignkey')  # type: ignore
    op.drop_column('go_a4_stream', 'website_id')
    op.add_column('go_a4', sa.Column('website_id', mysql.CHAR(length=32), nullable=False))
    op.create_foreign_key('go_a4_ibfk_2', 'go_a4', 'website', ['website_id'], ['id'])
    op.drop_constraint(None, 'go_a4', type_='unique')  # type: ignore
    # ### end Alembic commands ###
