"""added in id col for secondary table relationships

Revision ID: 728b15987040
Revises: 4087de0ca8d4
Create Date: 2025-01-28 09:39:07.905495

"""

import sqlalchemy as sa
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op

# revision identifiers, used by Alembic.
revision = "728b15987040"
down_revision = "4087de0ca8d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_platform", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(
        op.f("ix_client_platform_id"), "client_platform", ["id"], unique=True
    )
    op.add_column(
        "client_website", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(op.f("ix_client_website_id"), "client_website", ["id"], unique=True)
    op.add_column(
        "user_client", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(op.f("ix_user_client_id"), "user_client", ["id"], unique=True)
    op.add_column(
        "user_ipaddress", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(op.f("ix_user_ipaddress_id"), "user_ipaddress", ["id"], unique=True)
    op.add_column(
        "website_go_a4", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(op.f("ix_website_go_a4_id"), "website_go_a4", ["id"], unique=True)
    op.add_column(
        "website_go_ads", sa.Column("id", UUIDType(binary=False), nullable=False)
    )
    op.create_index(op.f("ix_website_go_ads_id"), "website_go_ads", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_website_go_ads_id"), table_name="website_go_ads")
    op.drop_column("website_go_ads", "id")
    op.drop_index(op.f("ix_website_go_a4_id"), table_name="website_go_a4")
    op.drop_column("website_go_a4", "id")
    op.drop_index(op.f("ix_user_ipaddress_id"), table_name="user_ipaddress")
    op.drop_column("user_ipaddress", "id")
    op.drop_index(op.f("ix_user_client_id"), table_name="user_client")
    op.drop_column("user_client", "id")
    op.drop_index(op.f("ix_client_website_id"), table_name="client_website")
    op.drop_column("client_website", "id")
    op.drop_index(op.f("ix_client_platform_id"), table_name="client_platform")
    op.drop_column("client_platform", "id")
    # ### end Alembic commands ###
