"""added table tracking_link and client_tracking_link

Revision ID: 88e10e674783
Revises: 355f1987cdd3
Create Date: 2024-08-06 10:58:16.165384

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.uuid import UUIDType  # type: ignore

# revision identifiers, used by Alembic.
revision = '88e10e674783'
down_revision = '355f1987cdd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_link',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_tracking_link_id'), 'tracking_link', ['id'], unique=True)
    op.create_table('client_tracking_link',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('client_id', UUIDType(binary=False), nullable=False),
    sa.Column('tracking_link_id', UUIDType(binary=False), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_link.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'tracking_link_id')
    )
    op.create_index(op.f('ix_client_tracking_link_id'), 'client_tracking_link', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_tracking_link_id'), table_name='client_tracking_link')
    op.drop_table('client_tracking_link')
    op.drop_index(op.f('ix_tracking_link_id'), table_name='tracking_link')
    op.drop_table('tracking_link')
    # ### end Alembic commands ###
