"""rebuilt fixed fk on website go_ads

Revision ID: 94b49836df08
Revises: b98b0f62cf71
Create Date: 2025-01-19 20:30:37.824520

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types.uuid import UUIDType

from alembic import op
from app.db.custom_types.longtext import LongText

# revision identifiers, used by Alembic.
revision = "94b49836df08"
down_revision = "b98b0f62cf71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gcft_snap_hotspotclick",
        "hotspot_content",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=True,
    )
    op.add_column(
        "go_ads", sa.Column("website_id", UUIDType(binary=False), nullable=False)
    )
    op.create_foreign_key(None, "go_ads", "website", ["website_id"], ["id"])
    op.alter_column(
        "go_sc_country",
        "keys",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_device",
        "keys",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_page",
        "keys",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_query",
        "keys",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_searchappearance",
        "keys",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "website_keywordcorpus",
        "corpus",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    op.alter_column(
        "website_keywordcorpus",
        "rawtext",
        existing_type=mysql.LONGBLOB(),
        type_=LongText(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "website_keywordcorpus",
        "rawtext",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "website_keywordcorpus",
        "corpus",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_searchappearance",
        "keys",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_query",
        "keys",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_page",
        "keys",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_device",
        "keys",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "go_sc_country",
        "keys",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "go_ads", type_="foreignkey")
    op.drop_column("go_ads", "website_id")
    op.alter_column(
        "gcft_snap_hotspotclick",
        "hotspot_content",
        existing_type=LongText(),
        type_=mysql.LONGBLOB(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
