"""empty message

Revision ID: 9e3b8c0f26cb
Revises: 
Create Date: 2023-01-22 18:18:04.398594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3b8c0f26cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=96), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_client_created_on'), 'client', ['created_on'], unique=False)
    op.create_table('geocoord',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(precision=20), nullable=False),
    sa.Column('longitude', sa.Float(precision=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_geocoord_created_on'), 'geocoord', ['created_on'], unique=False)
    op.create_table('website',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_secure', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_website_created_on'), 'website', ['created_on'], unique=False)
    op.create_table('client_website',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_client_website_created_on'), 'client_website', ['created_on'], unique=False)
    op.create_table('gcft',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('group_slug', sa.String(length=12), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_created_on'), 'gcft', ['created_on'], unique=False)
    op.create_table('go_a4',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('measurement_id', sa.String(length=16), nullable=False),
    sa.Column('property_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_a4_created_on'), 'go_a4', ['created_on'], unique=False)
    op.create_table('go_cloud',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_api_key', sa.String(length=64), nullable=False),
    sa.Column('hashed_project_id', sa.String(length=64), nullable=False),
    sa.Column('hashed_project_number', sa.String(length=64), nullable=False),
    sa.Column('hashed_service_account', sa.String(length=64), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_cloud_created_on'), 'go_cloud', ['created_on'], unique=False)
    op.create_table('go_sc',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_created_on'), 'go_sc', ['created_on'], unique=False)
    op.create_table('go_ua',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tracking_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_ua_created_on'), 'go_ua', ['created_on'], unique=False)
    op.create_table('imageupload',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_geotagged', sa.Boolean(), nullable=True),
    sa.Column('user_id', app.db.types.guid.GUID(), nullable=True),
    sa.Column('geocoord_id', app.db.types.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoord.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_imageupload_created_on'), 'imageupload', ['created_on'], unique=False)
    op.create_table('ipaddress',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('geocoord_id', app.db.types.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoord.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ipaddress_created_on'), 'ipaddress', ['created_on'], unique=False)
    op.create_table('note',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_note_created_on'), 'note', ['created_on'], unique=False)
    op.create_table('sharpspring',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hashed_api_key', sa.String(length=64), nullable=False),
    sa.Column('hashed_secret_key', sa.String(length=64), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sharpspring_created_on'), 'sharpspring', ['created_on'], unique=False)
    op.create_table('user_client',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('client_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_client_created_on'), 'user_client', ['created_on'], unique=False)
    op.create_table('website_map',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_website_map_created_on'), 'website_map', ['created_on'], unique=False)
    op.create_table('gcft_snap',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snap_name', sa.String(length=255), nullable=False),
    sa.Column('snap_slug', sa.String(length=12), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=False),
    sa.Column('geocoord_id', app.db.types.guid.GUID(), nullable=True),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['geocoord_id'], ['geocoord.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_created_on'), 'gcft_snap', ['created_on'], unique=False)
    op.create_table('go_a4_stream',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stream_id', sa.String(length=16), nullable=False),
    sa.Column('ga4_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['ga4_id'], ['go_a4.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_a4_stream_created_on'), 'go_a4_stream', ['created_on'], unique=False)
    op.create_table('go_sc_country',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keys', sa.String(length=10), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(precision=20), nullable=False),
    sa.Column('position', sa.Float(precision=20), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gsc_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_id'], ['go_sc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_country_created_on'), 'go_sc_country', ['created_on'], unique=False)
    op.create_table('go_sc_device',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keys', sa.String(length=100), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(precision=20), nullable=False),
    sa.Column('position', sa.Float(precision=20), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gsc_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_id'], ['go_sc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_device_created_on'), 'go_sc_device', ['created_on'], unique=False)
    op.create_table('go_sc_page',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keys', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(precision=20), nullable=False),
    sa.Column('position', sa.Float(precision=20), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gsc_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_id'], ['go_sc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_page_created_on'), 'go_sc_page', ['created_on'], unique=False)
    op.create_table('go_sc_query',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keys', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(precision=20), nullable=False),
    sa.Column('position', sa.Float(precision=20), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gsc_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_id'], ['go_sc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_query_created_on'), 'go_sc_query', ['created_on'], unique=False)
    op.create_table('go_sc_searchappearance',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keys', sa.String(length=100), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(precision=20), nullable=False),
    sa.Column('position', sa.Float(precision=20), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gsc_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gsc_id'], ['go_sc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_sc_searchappearance_created_on'), 'go_sc_searchappearance', ['created_on'], unique=False)
    op.create_table('go_ua_view',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('view_id', sa.String(length=16), nullable=False),
    sa.Column('gua_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gua_id'], ['go_ua.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_go_ua_view_created_on'), 'go_ua_view', ['created_on'], unique=False)
    op.create_table('user_ipaddress',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('ipaddress_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['ipaddress_id'], ['ipaddress.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_ipaddress_created_on'), 'user_ipaddress', ['created_on'], unique=False)
    op.create_table('website_page',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('sitemap_id', app.db.types.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['sitemap_id'], ['website_map.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_website_page_created_on'), 'website_page', ['created_on'], unique=False)
    op.create_table('gcft_snap_activeduration',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.DateTime(), nullable=False),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('snap_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['gcft_snap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_activeduration_created_on'), 'gcft_snap_activeduration', ['created_on'], unique=False)
    op.create_table('gcft_snap_browserreport',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('browser_version', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('platform_version', sa.String(length=255), nullable=True),
    sa.Column('desktop', sa.Boolean(), nullable=True),
    sa.Column('tablet', sa.Boolean(), nullable=True),
    sa.Column('mobile', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('snap_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['gcft_snap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_browserreport_created_on'), 'gcft_snap_browserreport', ['created_on'], unique=False)
    op.create_table('gcft_snap_hotspotclick',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_id', sa.String(length=255), nullable=True),
    sa.Column('hotspot_type_name', sa.String(length=32), nullable=True),
    sa.Column('hotspot_content', sa.Text(), nullable=True),
    sa.Column('hotspot_icon_name', sa.String(length=255), nullable=True),
    sa.Column('hotspot_name', sa.String(length=255), nullable=True),
    sa.Column('hotspot_user_icon_name', sa.String(length=255), nullable=True),
    sa.Column('linked_snap_name', sa.String(length=255), nullable=True),
    sa.Column('snap_file_name', sa.String(length=255), nullable=True),
    sa.Column('icon_color', sa.String(length=20), nullable=True),
    sa.Column('bg_color', sa.String(length=20), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('hotspot_update_date', sa.DateTime(), nullable=False),
    sa.Column('click_date', sa.DateTime(), nullable=False),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('snap_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['gcft_snap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_hotspotclick_created_on'), 'gcft_snap_hotspotclick', ['created_on'], unique=False)
    op.create_table('gcft_snap_trafficsource',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=False),
    sa.Column('utm_campaign', sa.String(length=255), nullable=False),
    sa.Column('utm_content', sa.String(length=255), nullable=False),
    sa.Column('utm_medium', sa.String(length=255), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=False),
    sa.Column('utm_term', sa.String(length=255), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('snap_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['gcft_snap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_trafficsource_created_on'), 'gcft_snap_trafficsource', ['created_on'], unique=False)
    op.create_table('gcft_snap_view',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('view_date', sa.DateTime(), nullable=False),
    sa.Column('gcft_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('snap_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gcft_id'], ['gcft.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['gcft_snap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_gcft_snap_view_created_on'), 'gcft_snap_view', ['created_on'], unique=False)
    op.create_table('website_keywordcorpus',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corpus', sa.Text(), nullable=True),
    sa.Column('rawtext', sa.Text(), nullable=True),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('page_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_page.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_website_keywordcorpus_created_on'), 'website_keywordcorpus', ['created_on'], unique=False)
    op.create_table('website_pagespeedinsights',
    sa.Column('id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ps_grade', sa.Float(), nullable=False),
    sa.Column('ps_value', sa.Float(), nullable=False),
    sa.Column('fcp_grade', sa.Float(), nullable=False),
    sa.Column('fcp_value', sa.Float(), nullable=False),
    sa.Column('lcp_grade', sa.Float(), nullable=False),
    sa.Column('lcp_value', sa.Float(), nullable=False),
    sa.Column('cls_grade', sa.Float(), nullable=False),
    sa.Column('cls_value', sa.Float(), nullable=False),
    sa.Column('si_grade', sa.Float(), nullable=False),
    sa.Column('si_value', sa.Float(), nullable=False),
    sa.Column('tbt_grade', sa.Float(), nullable=False),
    sa.Column('tbt_value', sa.Float(), nullable=False),
    sa.Column('i_grade', sa.Float(), nullable=False),
    sa.Column('i_value', sa.Float(), nullable=False),
    sa.Column('page_id', app.db.types.guid.GUID(), nullable=False),
    sa.Column('website_id', app.db.types.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_page.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_website_pagespeedinsights_created_on'), 'website_pagespeedinsights', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_pagespeedinsights_created_on'), table_name='website_pagespeedinsights')
    op.drop_table('website_pagespeedinsights')
    op.drop_index(op.f('ix_website_keywordcorpus_created_on'), table_name='website_keywordcorpus')
    op.drop_table('website_keywordcorpus')
    op.drop_index(op.f('ix_gcft_snap_view_created_on'), table_name='gcft_snap_view')
    op.drop_table('gcft_snap_view')
    op.drop_index(op.f('ix_gcft_snap_trafficsource_created_on'), table_name='gcft_snap_trafficsource')
    op.drop_table('gcft_snap_trafficsource')
    op.drop_index(op.f('ix_gcft_snap_hotspotclick_created_on'), table_name='gcft_snap_hotspotclick')
    op.drop_table('gcft_snap_hotspotclick')
    op.drop_index(op.f('ix_gcft_snap_browserreport_created_on'), table_name='gcft_snap_browserreport')
    op.drop_table('gcft_snap_browserreport')
    op.drop_index(op.f('ix_gcft_snap_activeduration_created_on'), table_name='gcft_snap_activeduration')
    op.drop_table('gcft_snap_activeduration')
    op.drop_index(op.f('ix_website_page_created_on'), table_name='website_page')
    op.drop_table('website_page')
    op.drop_index(op.f('ix_user_ipaddress_created_on'), table_name='user_ipaddress')
    op.drop_table('user_ipaddress')
    op.drop_index(op.f('ix_go_ua_view_created_on'), table_name='go_ua_view')
    op.drop_table('go_ua_view')
    op.drop_index(op.f('ix_go_sc_searchappearance_created_on'), table_name='go_sc_searchappearance')
    op.drop_table('go_sc_searchappearance')
    op.drop_index(op.f('ix_go_sc_query_created_on'), table_name='go_sc_query')
    op.drop_table('go_sc_query')
    op.drop_index(op.f('ix_go_sc_page_created_on'), table_name='go_sc_page')
    op.drop_table('go_sc_page')
    op.drop_index(op.f('ix_go_sc_device_created_on'), table_name='go_sc_device')
    op.drop_table('go_sc_device')
    op.drop_index(op.f('ix_go_sc_country_created_on'), table_name='go_sc_country')
    op.drop_table('go_sc_country')
    op.drop_index(op.f('ix_go_a4_stream_created_on'), table_name='go_a4_stream')
    op.drop_table('go_a4_stream')
    op.drop_index(op.f('ix_gcft_snap_created_on'), table_name='gcft_snap')
    op.drop_table('gcft_snap')
    op.drop_index(op.f('ix_website_map_created_on'), table_name='website_map')
    op.drop_table('website_map')
    op.drop_index(op.f('ix_user_client_created_on'), table_name='user_client')
    op.drop_table('user_client')
    op.drop_index(op.f('ix_sharpspring_created_on'), table_name='sharpspring')
    op.drop_table('sharpspring')
    op.drop_index(op.f('ix_note_created_on'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_ipaddress_created_on'), table_name='ipaddress')
    op.drop_table('ipaddress')
    op.drop_index(op.f('ix_imageupload_created_on'), table_name='imageupload')
    op.drop_table('imageupload')
    op.drop_index(op.f('ix_go_ua_created_on'), table_name='go_ua')
    op.drop_table('go_ua')
    op.drop_index(op.f('ix_go_sc_created_on'), table_name='go_sc')
    op.drop_table('go_sc')
    op.drop_index(op.f('ix_go_cloud_created_on'), table_name='go_cloud')
    op.drop_table('go_cloud')
    op.drop_index(op.f('ix_go_a4_created_on'), table_name='go_a4')
    op.drop_table('go_a4')
    op.drop_index(op.f('ix_gcft_created_on'), table_name='gcft')
    op.drop_table('gcft')
    op.drop_index(op.f('ix_client_website_created_on'), table_name='client_website')
    op.drop_table('client_website')
    op.drop_index(op.f('ix_website_created_on'), table_name='website')
    op.drop_table('website')
    op.drop_index(op.f('ix_geocoord_created_on'), table_name='geocoord')
    op.drop_table('geocoord')
    op.drop_index(op.f('ix_client_created_on'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
