"""removed bdx and sharpspring api tables

Revision ID: a006ff43d0a4
Revises: 94b49836df08
Create Date: 2025-01-24 18:54:25.990073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a006ff43d0a4'
down_revision = '94b49836df08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bdx_feed_id', table_name='bdx_feed')
    op.drop_index('ix_bdx_feed_xml_file_key', table_name='bdx_feed')
    op.drop_table('bdx_feed')
    op.drop_index('ix_sharpspring_id', table_name='sharpspring')
    op.drop_table('sharpspring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharpspring',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('api_key', mysql.VARCHAR(length=704), nullable=False),
    sa.Column('secret_key', mysql.VARCHAR(length=704), nullable=False),
    sa.Column('platform_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('client_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='sharpspring_ibfk_2'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='sharpspring_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sharpspring_id', 'sharpspring', ['id'], unique=True)
    op.create_table('bdx_feed',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=704), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=704), nullable=False),
    sa.Column('serverhost', mysql.VARCHAR(length=704), nullable=False),
    sa.Column('xml_file_key', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('platform_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('client_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='bdx_feed_ibfk_2'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='bdx_feed_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_bdx_feed_xml_file_key', 'bdx_feed', ['xml_file_key'], unique=True)
    op.create_index('ix_bdx_feed_id', 'bdx_feed', ['id'], unique=True)
    # ### end Alembic commands ###
