"""altered tracking links db table

Revision ID: b7f0de526452
Revises: 1bc48e91aa39
Create Date: 2024-09-26 13:00:17.572436

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7f0de526452"
down_revision = "1bc48e91aa39"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracking_link", sa.Column("scheme", sa.String(length=16), nullable=False)
    )
    op.add_column(
        "tracking_link", sa.Column("domain", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "tracking_link",
        sa.Column("destination", sa.String(length=2048), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("tracking_link", "destination")
    op.drop_column("tracking_link", "domain")
    # ### end Alembic commands ###
