"""revised bdx feed table

Revision ID: c934ef207888
Revises: 67ab88f410ce
Create Date: 2024-04-28 14:04:00.705835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.db.custom_types import LongText

# revision identifiers, used by Alembic.
revision = 'c934ef207888'
down_revision = '67ab88f410ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='bdx_feed')
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.create_index('username', 'bdx_feed', ['username'], unique=True)
    # ### end Alembic commands ###
