"""updated IPaddress table

Revision ID: cce84fb59468
Revises: eea0802b7269
Create Date: 2024-04-24 20:02:25.502074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils  # type: ignore
from app.db.custom_types import LongText

# revision identifiers, used by Alembic.
revision = 'cce84fb59468'
down_revision = 'eea0802b7269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipaddress', sa.Column('org', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=704), nullable=True))
    op.add_column('ipaddress', sa.Column('postal', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.add_column('ipaddress', sa.Column('timezone', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=472), nullable=True))
    op.add_column('ipaddress', sa.Column('country_name', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=704), nullable=True))
    op.add_column('ipaddress', sa.Column('is_eu', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=428), nullable=True))
    op.add_column('ipaddress', sa.Column('country_flag_url', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=3116), nullable=True))
    op.add_column('ipaddress', sa.Column('country_flag_unicode', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=704), nullable=True))
    op.add_column('ipaddress', sa.Column('country_currency_code', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.add_column('ipaddress', sa.Column('continent_code', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.add_column('ipaddress', sa.Column('continent_name', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.add_column('ipaddress', sa.Column('latitude', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.add_column('ipaddress', sa.Column('longitude', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=408), nullable=True))
    op.drop_column('ipaddress', 'isp')
    op.drop_column('ipaddress', 'location')
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.add_column('ipaddress', sa.Column('location', mysql.VARCHAR(length=704), nullable=True))
    op.add_column('ipaddress', sa.Column('isp', mysql.VARCHAR(length=704), nullable=True))
    op.drop_column('ipaddress', 'longitude')
    op.drop_column('ipaddress', 'latitude')
    op.drop_column('ipaddress', 'continent_name')
    op.drop_column('ipaddress', 'continent_code')
    op.drop_column('ipaddress', 'country_currency_code')
    op.drop_column('ipaddress', 'country_flag_unicode')
    op.drop_column('ipaddress', 'country_flag_url')
    op.drop_column('ipaddress', 'is_eu')
    op.drop_column('ipaddress', 'country_name')
    op.drop_column('ipaddress', 'timezone')
    op.drop_column('ipaddress', 'postal')
    op.drop_column('ipaddress', 'org')
    # ### end Alembic commands ###
