"""added url_path to tracking link table

Revision ID: d1c6da9a773a
Revises: 1e4c0ac33646
Create Date: 2024-09-11 12:07:59.281784

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d1c6da9a773a"
down_revision = "1e4c0ac33646"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracking_link", sa.Column("url_path", sa.String(length=2048), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracking_link", "url_path")
    # ### end Alembic commands ###
