"""altered go_cloud table

Revision ID: e84b73490a04
Revises: c934ef207888
Create Date: 2024-04-28 20:14:51.670740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils  # type: ignore
from app.db.custom_types import LongText

# revision identifiers, used by Alembic.
revision = 'e84b73490a04'
down_revision = 'c934ef207888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('go_cloud', 'project_id',
               existing_type=mysql.VARCHAR(length=704),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=472),
               existing_nullable=False)
    op.alter_column('go_cloud', 'project_number',
               existing_type=mysql.VARCHAR(length=704),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=472),
               existing_nullable=False)
    op.alter_column('go_cloud', 'service_account',
               existing_type=mysql.VARCHAR(length=704),
               nullable=True)
    op.create_unique_constraint(None, 'go_cloud', ['project_number'])
    op.create_unique_constraint(None, 'go_cloud', ['project_id'])
    op.create_unique_constraint(None, 'go_cloud', ['service_account'])
    op.drop_column('go_cloud', 'api_key')
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=mysql.LONGBLOB(),
               type_=LongText(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_keywordcorpus', 'rawtext',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.alter_column('website_keywordcorpus', 'corpus',
               existing_type=LongText(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
    op.add_column('go_cloud', sa.Column('api_key', mysql.VARCHAR(length=704), nullable=False))
    op.drop_constraint(None, 'go_cloud', type_='unique')  # type: ignore
    op.drop_constraint(None, 'go_cloud', type_='unique')  # type: ignore
    op.drop_constraint(None, 'go_cloud', type_='unique')  # type: ignore
    op.alter_column('go_cloud', 'service_account',
               existing_type=mysql.VARCHAR(length=704),
               nullable=False)
    op.alter_column('go_cloud', 'project_number',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=472),
               type_=mysql.VARCHAR(length=704),
               existing_nullable=False)
    op.alter_column('go_cloud', 'project_id',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=472),
               type_=mysql.VARCHAR(length=704),
               existing_nullable=False)
    # ### end Alembic commands ###
