ERROR_MESSAGE_ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
ERROR_MESSAGE_ORGANIZATION_EXISTS = "ORGANIZATION_EXISTS"
ERROR_MESSAGE_ORGANIZATION_RELATIONSHOP_NOT_FOUND = (
    "ORGANIZATION_RELATIONSHOP_NOT_FOUND"
)
